version: 2

build:
  # Install our python package before building the docs
  os: "ubuntu-20.04"
  tools:
    python:
      install:
        - method: pip
          path: .
    
sphinx:
  fail_on_warning: true
  
formats:
  - pdf
  - epub